#!/usr/bin/env python3
"""Write analysis/PAPER_TABLE.md and analysis/paper_table.csv from analysis/paper_table.json (run aggregate.py first)."""
import json, sys, os, csv
P = sys.argv[1]
rows = json.load(open(os.path.join(P, "analysis", "paper_table.json")))
import glob
_lc = {json.load(open(f))["key"]: json.load(open(f)).get("load_class", "") for f in glob.glob(os.path.join(P, "records", "*.json"))}
_tier = {}
try:
    for r in json.load(open(os.path.join(P, "deck", "data", "tail_tiers.json")))["rows"]:
        if r["row_id"].startswith("all|") and "keys" in r:
            for k in r["keys"]: _tier[k] = r["tier"]
except Exception: pass
for x in rows: x["load_class"] = _lc.get(x["key"], ""); x["tier"] = _tier.get(x["key"], "")
order = sorted(rows, key=lambda x: (x["mp"], x["read"] != "full", str(x["layer"]), x["year"] or 0))
def fmt(l): return ", ".join(l) if l else "—"
with open(os.path.join(P, "analysis", "PAPER_TABLE.md"), "w") as fh:
    fh.write("# Per-paper table: what each paper optimizes\n\nGenerated by scripts/paper_table_md.py from records/*.json "
             "(normalization rules N1–N7 in RESEARCH_LOG.md; tail roles from qa/TAIL_AUDIT.md). Objective/constraint cells list "
             "canonical code@statistic as recorded (n/a = no statistic stated). read = full | abstract. MP = metric/benchmark paper.\n\n")
    sec = None
    for x in order:
        s = "Metric/benchmark papers (MP)" if x["mp"] else ("Full-text optimizers" if x["read"] == "full" else "Abstract-only optimizers (bonus)")
        if s != sec:
            sec = s; fh.write(f"\n## {s}\n\n| Key | Title | Year | Layer | Load class | Objective | Constraint | Tail tier |\n|---|---|---|---|---|---|---|---|\n")
        fh.write(f"| {x['key']} | {x['title'].replace('|','/')} | {x['year']} | {x['layer']} | {x['load_class']} | {fmt(x['obj_stats'])} | {fmt(x['con_stats'])} | {x['tier']} |\n")
with open(os.path.join(P, "analysis", "paper_table.csv"), "w", newline="") as fh:
    w = csv.writer(fh); w.writerow(["key","title","year","layer","read","metric_paper","objective_families","constraint_families","objective","constraint","tail_role","eval_type","load_class","tail_tier"])
    for x in order: w.writerow([x["key"],x["title"],x["year"],x["layer"],x["read"],x["mp"],";".join(x["objf"]),";".join(x["conf_"]),";".join(x["obj_stats"]),";".join(x["con_stats"]),x.get("tail_role",""),x["eval_type"],x["load_class"],x["tier"]])
print("ok", len(rows))
